"use client";

import { useState, useEffect } from "react";
import { usePathname } from "next/navigation";
import { Eye, EyeOff, Bell, ChevronDown, Circle, Database } from "lucide-react";
import { cn } from "@/lib/utils";
import { formatCurrency } from "@/lib/utils";
import { api } from "@/lib/api";

const PAGE_META: Record<string, { title: string; description: string }> = {
  "/dashboard":  { title: "Dashboard",   description: "Your portfolio overview and live market data" },
  "/signals":    { title: "Signals",     description: "Buy and sell signals generated by your strategies" },
  "/positions":  { title: "Positions",   description: "All your open and closed trades" },
  "/strategies": { title: "Strategies",  description: "Your trading strategies and their performance" },
  "/backtest":   { title: "Backtest",    description: "Test a strategy against historical data" },
  "/settings":   { title: "Settings",    description: "Configure your broker, API keys, and risk limits" },
};

interface TopbarProps {
  masked: boolean;
  onToggleMask: () => void;
}

export function Topbar({ masked, onToggleMask }: TopbarProps) {
  const [notifOpen, setNotifOpen] = useState(false);
  const [dbConnected, setDbConnected] = useState(true);
  const [isDemo, setIsDemo] = useState(false);
  const pathname = usePathname() ?? "";

  useEffect(() => {
    api.health()
      .then((h) => {
        setIsDemo(h.broker === "mock");
        setDbConnected(h.database_connected);
      })
      .catch(() => setDbConnected(false));

    // Poll status every 30 seconds
    const timer = setInterval(() => {
      api.health()
        .then((h) => setDbConnected(h.database_connected))
        .catch(() => setDbConnected(false));
    }, 30000);

    return () => clearInterval(timer);
  }, []);
  const meta = PAGE_META[pathname] ?? { title: "AlgoTrade", description: "" };

  return (
    <header className="flex items-center justify-between px-6 py-0 border-b border-zinc-800/60 bg-zinc-950/80 backdrop-blur-sm shrink-0 h-14 gap-4">
      {/* Left: page name + description */}
      <div className="min-w-0">
        <h1 className="text-sm font-semibold text-zinc-100 leading-none">{meta.title}</h1>
        {meta.description && (
          <p className="text-[11px] text-zinc-500 leading-none mt-0.5 truncate hidden sm:block">
            {meta.description}
          </p>
        )}
      </div>

      {/* Right: controls */}
      <div className="flex items-center gap-2 shrink-0">
        {/* Demo mode badge — only shown when broker=mock */}
        {isDemo && (
          <div className="hidden sm:flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-amber-500/10 border border-amber-500/20">
            <span className="w-1.5 h-1.5 rounded-full bg-amber-400 shrink-0" aria-hidden />
            <span className="text-xs text-amber-400 font-medium">Demo Mode</span>
          </div>
        )}

        {/* Database status */}
        <div className={cn(
          "hidden md:flex items-center gap-1.5 px-2.5 py-1 rounded-lg border",
          dbConnected 
            ? "bg-emerald-500/10 border-emerald-500/20" 
            : "bg-rose-500/10 border-rose-500/20"
        )}>
          <Database className={cn(
            "w-3 h-3",
            dbConnected ? "text-emerald-400" : "text-rose-400"
          )} aria-hidden />
          <span className={cn("text-xs font-medium", dbConnected ? "text-emerald-400" : "text-rose-400")}>
            {dbConnected ? "Connected" : "Offline"}
          </span>
        </div>

        {/* Market status */}
        <div className="hidden md:flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-zinc-800/60 border border-zinc-700/40">
          <Circle className="w-2 h-2 fill-emerald-400 text-emerald-400" aria-hidden />
          <span className="text-xs text-zinc-400">Market Open</span>
        </div>

        {/* Balance toggle */}
        <button
          onClick={onToggleMask}
          className="hidden lg:flex items-center gap-2 px-3 py-1.5 rounded-lg bg-zinc-800/60 border border-zinc-700/40 hover:bg-zinc-800 transition-colors group"
          aria-label={masked ? "Show balance" : "Hide balance"}
        >
          <span className="text-xs text-zinc-400">Balance</span>
          <span className="text-sm font-medium text-zinc-100 tabular-nums">
            {formatCurrency(124_850.32, { masked })}
          </span>
          <span className="text-zinc-500 group-hover:text-zinc-300 transition-colors">
            {masked ? <Eye className="w-3.5 h-3.5" /> : <EyeOff className="w-3.5 h-3.5" />}
          </span>
        </button>

        {/* Notifications */}
        <div className="relative">
          <button
            onClick={() => setNotifOpen((o) => !o)}
            className="relative flex items-center justify-center w-9 h-9 rounded-lg text-zinc-500 hover:text-zinc-200 hover:bg-zinc-800 transition-colors"
            aria-label="Notifications"
          >
            <Bell className="w-4 h-4" />
            <span className="absolute top-2 right-2 w-1.5 h-1.5 rounded-full bg-emerald-400" aria-hidden />
          </button>
          {notifOpen && (
            <div className="absolute right-0 mt-2 w-72 rounded-xl border border-zinc-800 bg-zinc-900 shadow-xl z-50 py-2">
              <p className="px-4 py-2 text-xs font-medium text-zinc-500 uppercase tracking-wider">
                Notifications
              </p>
              <NotifItem type="success" message="Buy order for AAPL filled at $182.50" time="2m ago" />
              <NotifItem type="warning" message="Stop-loss triggered on TSLA position" time="14m ago" />
              <NotifItem type="info"    message="Strategy RSI-Reversion generated 3 signals" time="1h ago" />
            </div>
          )}
        </div>

        {/* Account avatar */}
        <button className="flex items-center gap-2 pl-1 pr-2 py-1 rounded-lg hover:bg-zinc-800 transition-colors">
          <div className="w-7 h-7 rounded-lg bg-emerald-500/20 flex items-center justify-center text-xs font-semibold text-emerald-400">
            JD
          </div>
          <ChevronDown className="w-3.5 h-3.5 text-zinc-500" aria-hidden />
        </button>
      </div>
    </header>
  );
}

function NotifItem({ type, message, time }: { type: "success" | "warning" | "info"; message: string; time: string }) {
  const dot = { success: "bg-emerald-400", warning: "bg-amber-400", info: "bg-blue-400" }[type];
  return (
    <div className="flex items-start gap-3 px-4 py-2.5 hover:bg-zinc-800/50 transition-colors cursor-default">
      <span className={cn("mt-1.5 w-1.5 h-1.5 rounded-full shrink-0", dot)} aria-hidden />
      <div className="flex-1 min-w-0">
        <p className="text-xs text-zinc-300 leading-relaxed">{message}</p>
        <p className="text-xs text-zinc-600 mt-0.5">{time}</p>
      </div>
    </div>
  );
}
