# file: src/events.py
"""
Typed event objects used throughout the event-driven pipeline.

Events flow: MarketEvent -> CandidateEvent -> OptionChainEvent
          -> SignalEvent -> OrderEvent -> FillEvent
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional


class SignalDirection(str, enum.Enum):
    CALL = "CALL"
    PUT = "PUT"


class OrderSide(str, enum.Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(str, enum.Enum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


@dataclass
class MarketQuote:
    """Normalised market quote for a single ticker."""
    symbol: str
    price: float
    change_pct: float
    volume: int
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class CandidateEvent:
    """Published by the screener when top-movers are refreshed."""
    gainers: List[MarketQuote]
    losers: List[MarketQuote]
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class OptionContract:
    """A single option contract with liquidity metadata."""
    symbol: str            # underlying
    expiry: str            # YYYY-MM-DD
    strike: float
    option_type: str       # "call" | "put"
    bid: float
    ask: float
    volume: int
    open_interest: int
    implied_volatility: float
    delta: float = 0.0
    underlying_price: float = 0.0

    @property
    def mid_price(self) -> float:
        return (self.bid + self.ask) / 2.0

    @property
    def spread_pct(self) -> float:
        if self.mid_price == 0:
            return float("inf")
        return (self.ask - self.bid) / self.mid_price


@dataclass
class OptionChainEvent:
    """Option chain after liquidity filtering for a given symbol."""
    symbol: str
    contracts: List[OptionContract]
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class TradePlan:
    """
    Structured trade proposal generated by the strategy engine.

    entry_limit  : limit price to use for the entry order (typically ask * 1.01)
    stop_loss    : price level at which to exit the position with a loss
    take_profit  : price level at which to exit with a profit
    position_size: number of contracts to trade (set by risk manager)
    """
    symbol: str
    direction: SignalDirection
    contract: OptionContract
    entry_limit: float
    stop_loss: float
    take_profit: float
    position_size: int = 1
    rsi: float = 0.0
    macd_hist: float = 0.0
    rationale: str = ""
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class SignalEvent:
    """Emitted by the strategy engine; carries a fully-formed TradePlan."""
    trade_plan: TradePlan
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class OrderEvent:
    """Tracks a broker order lifecycle."""
    order_id: str
    symbol: str
    option_symbol: str
    side: OrderSide
    quantity: int
    limit_price: float
    status: OrderStatus = OrderStatus.PENDING
    filled_qty: int = 0
    avg_fill_price: float = 0.0
    timestamps: Dict[str, datetime] = field(default_factory=dict)

    def transition(self, new_status: OrderStatus) -> None:
        self.status = new_status
        self.timestamps[new_status.value] = datetime.utcnow()


@dataclass
class FillEvent:
    """Emitted when an order reaches FILLED status."""
    order_id: str
    symbol: str
    option_symbol: str
    side: OrderSide
    quantity: int
    avg_fill_price: float
    timestamp: datetime = field(default_factory=datetime.utcnow)
